"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createContext, useState } from "react";
import { IAllIdolData } from "./components/Table";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Idol Management",
  description: "Generated by create next app",
};

export const DataContext = createContext<any>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [reRender, setReRender] = useState<boolean>(false);
  const [allIdolDataContext, setAllIdolDataContext] =
    useState<IAllIdolData[]>();
  const [filteredIdolContext, setFilteredIdolContext] =
    useState<IAllIdolData[]>();
  const [currentId, setCurrentId] = useState<any>();
  const [activeAPIgetIdolDetail, setActiveAPIgetIdolDetail] =
    useState<any>(false);

  return (
    <html lang="en">
      <DataContext.Provider
        value={{
          reRender,
          setReRender,
          allIdolDataContext,
          setAllIdolDataContext,
          filteredIdolContext,
          setFilteredIdolContext,
          currentId,
          setCurrentId,
          activeAPIgetIdolDetail,
          setActiveAPIgetIdolDetail,
        }}
      >
        <body className={inter.className}>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
        </body>
      </DataContext.Provider>
    </html>
  );
}
